name: Flutter Web Build and Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true
      
      - name: Check Flutter environment
        run: |
          flutter --version
          dart --version
      
      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get --no-example
      
      - name: Create required directories
        run: |
          mkdir -p assets/images
          mkdir -p assets/icons
          touch assets/images/.gitkeep
          touch assets/icons/.gitkeep
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Build web
        run: flutter build web --release --web-renderer canvaskit
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: build/web
          vercel-args: '--prod'
